### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by pasarn** [citrix/netscaler-metrics-exporter#14]
File "./exporter.py", line 274
    logger.error('Exiting since NS access test failed for nsip {}'.format(nsip) )

  File "./exporter.py", line 278
    logger.error('Invalid k8sprefix : non-alphanumeric not accepted')

**Comment by haroraCitrix** [comment]
Thanks for input, these and other similar corrections updated in file.
